### ISSUE TITLE
diffではなく本文まるごとやりとりする

### ISSUE THREAD

**Issue by shokai** [shokai/semirara#20]
Editor componentの変更コマンドも付ける

diffは複数行変更がある時うまくいかなかった

**Comment by shokai** [comment]
とりあえず、jsondiffpatchでの変更判定はそのままで、そこから本文まるごと送信する。
のちのち変更判定を自前実装に入れ替える

変更を受け取った別のclient側で、更新された行の場所を検知してeditlineを上下させる必要がある。そこも自前でできるだろうか？

**Comment by shokai** [comment]
upsert使ったら新規作成したページにエラーがでた

```
MongoError: exception: E11000 duplicate key error index: semirara.pages.$number_1 dup key: { : null }
    at Function.MongoError.create (/Users/sho/src/nodejs/semirara/node_modules/mongodb-core/lib/error.js:31:11)
    at commandCallback (/Users/sho/src/nodejs/semirara/node_modules/mongodb-core/lib/topologies/server.js:1154:66)
    at [object Object].Callbacks.emit (/Users/sho/src/nodejs/semirara/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at [object Object].messageHandler (/Users/sho/src/nodejs/semirara/node_modules/mongodb-core/lib/topologies/server.js:295:23)
    at Socket.<anonymous> (/Users/sho/src/nodejs/semirara/node_modules/mongodb-core/lib/connection/connection.js:285:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)
```

**Comment by shokai** [comment]
## jsondiffpatchを削除する
- [x] 行に変更があったかどうか自前で判定する

**Comment by shokai** [comment]
upsertはmongoose middlewareが動かないので使わない事にした
