### ISSUE TITLE
memjs memory leak

### ISSUE THREAD

**Issue by shokai** [shokai/semirara#34]
```
(node) warning: possible EventEmitter memory leak detected. 11 timeout listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:252:17)
    at Socket.Readable.on (_stream_readable.js:673:33)
    at Socket.once (events.js:278:8)
    at Socket.setTimeout (net.js:315:12)
    at /Users/sho/src/nodejs/semirara/node_modules/memjs/lib/memjs/server.js:156:7
    at [object Object].Server.sock (/Users/sho/src/nodejs/semirara/node_modules/memjs/lib/memjs/server.js:148:5)
    at [object Object].Server.write (/Users/sho/src/nodejs/semirara/node_modules/memjs/lib/memjs/server.js:154:8)
    at [object Object].Client.perform (/Users/sho/src/nodejs/semirara/node_modules/memjs/lib/memjs/memjs.js:519:8)
    at [object Object].Client.get (/Users/sho/src/nodejs/semirara/node_modules/memjs/lib/memjs/memjs.js:114:8)
    at cache.es6:34:14
    at new Promise (/Users/sho/src/nodejs/semirara/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)
    at Cache.get (cache.es6:31:12)
    at Function._callee$ (page.es6:73:26)
    at tryCatch (/Users/sho/src/nodejs/semirara/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/sho/src/nodejs/semirara/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/sho/src/nodejs/semirara/node_modules/babel-regenerator-runtime/runtime.js:94:21)
```

**Comment by shokai** [comment]
memjsから[memcached](https://www.npmjs.com/package/memcached)に切り替えた

**Comment by shokai** [comment]
memcachedはbinaryプロトコルサポートしてなくてSASL認証できないんだった

**Comment by shokai** [comment]
よくわからないからいいか
